a=int(input("Real part of Complex Number 1: "))
b=int(input("Imaginary part of Complex Number 1: "))
c=int(input("Real part of Complex Number 2: "))
d=int(input("Imaginary part of Complex Number 2: "))
a1=str(a)
b1=str(b)
c1=str(c)
d1=str(d)
print("Complex Number 1: "+a1+"+"+b1+"i")
print("Complex Number 1: "+c1+"+"+d1+"i")
addFront=str(a+c)
addCom=str(b+d)
subFront=str(a-c)
subCom=str(b-d)
mulFront=str(a*c-b*d)
mulCom=str(a*d+b*c)
divFront=str((a*c+b*d)/(c**2+d**2))
divCom=str((b*c-a*d)/(c**2+d**2))
print("Addition: "+addFront+"+"+addCom+"i")
print("Subtraction: "+subFront+"+"+subCom+"i")
print("Multiplication: "+mulFront+"+"+mulCom+"i")
print("Division: "+divFront+"+"+divCom+"i")